# -*- coding: utf-8 -*-
"""data_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DdCLikFPIJfL5ctPlY5vHcfgjrMaBSMo
"""

from google.colab import drive
drive.mount('/content/drive/')

import os 

# Set your working directory to a folder in your Google Drive. This way, if your notebook times out,
# your files will be saved in your Google Drive!

# the base Google Drive directory
root_dir = "/content/drive/My Drive/"

# choose where you want your project files to be saved
project_folder = "Colab Notebooks/My Project Folder/"

def create_and_set_working_directory(project_folder):
  # check if your project folder exists. if not, it will be created.
  if os.path.isdir(root_dir + project_folder) == False:
    os.mkdir(root_dir + project_folder)
    print(root_dir + project_folder + ' did not exist but was created.')

  # change the OS to use your project folder as the working directory
  os.chdir(root_dir + project_folder)

  # create a test file to make sure it shows up in the right place
  !touch 'new_file_in_working_directory.txt'
  print('\nYour working directory was changed to ' + root_dir + project_folder + \
        "\n\nAn empty text file was created there. You can also run !pwd to confirm the current working directory." )

create_and_set_working_directory(project_folder)

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My\ Drive/

!ls

import os
os.chdir('/content/drive/My Drive/veri_artirma/')

from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array, load_img #farklı kutuphaneler

# kullanılacak veri artırma tekniklerini tanımla
datagen = ImageDataGenerator(rotation_range=40,
                             width_shift_range=0.2,
                             height_shift_range=0.2,
                             shear_range=0.2,
                             zoom_range=0.2,
                             horizontal_flip=True,
                             vertical_flip=True,
                             fill_mode='nearest')

img = load_img('araguler.jpg')
x = img_to_array(img)
x = x.reshape((1,) + x.shape)

# tek resimden 50 tane farklı resim üret ve Artirilmis_Veri klasörüne .jpeg formatında kaydet.
i = 0

for batch in datagen.flow(x, batch_size=1,
                          save_to_dir='/content/drive/My Drive/veri_artirma/artirilmis_veri', 
                          save_format='jpg'):
    i += 1
    if i > 50:
        break

